#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/home/vineet/Desktop/lanlab/AndrABEn/ProvaJNI/jni/ABE-Dependencies/android-toolchain/bin/arm-linux-androideabi-gcc-4.6 -march=armv7-a -mfloat-abi=softfp --sysroot=/home/vineet/Android/android-ndk-r9b/platforms/android-9/arch-arm -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android-armv7"
  #define DATE "Wed Mar 30 01:48:22 IST 2016"
#endif
