#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/','v','i',
        'n','e','e','t','/','D','e','s','k','t','o','p','/','l','a','n','l','a',
        'b','/','A','n','d','r','A','B','E','n','/','P','r','o','v','a','J','N',
        'I','/','j','n','i','/','A','B','E','-','D','e','p','e','n','d','e','n',
        'c','i','e','s','/','a','n','d','r','o','i','d','-','t','o','o','l','c',
        'h','a','i','n','/','b','i','n','/','a','r','m','-','l','i','n','u','x',
        '-','a','n','d','r','o','i','d','e','a','b','i','-','g','c','c','-','4',
        '.','9',' ','-','m','a','r','c','h','=','a','r','m','v','7','-','a',' ',
        '-','m','f','l','o','a','t','-','a','b','i','=','s','o','f','t','f','p',
        ' ','-','-','s','y','s','r','o','o','t','=','/','h','o','m','e','/','v',
        'i','n','e','e','t','/','A','n','d','r','o','i','d','/','a','n','d','r',
        'o','i','d','-','n','d','k','-','r','1','1','b','/','p','l','a','t','f',
        'o','r','m','s','/','a','n','d','r','o','i','d','-','9','/','a','r','c',
        'h','-','a','r','m',' ','-','I','.',' ','-','I','.','.',' ','-','I','.',
        '.','/','i','n','c','l','u','d','e',' ',' ','-','D','O','P','E','N','S',
        'S','L','_','T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N',
        'T','R','A','N','T',' ','-','D','D','S','O','_','D','L','F','C','N',' ',
        '-','D','H','A','V','E','_','D','L','F','C','N','_','H',' ','-','m','a',
        'r','c','h','=','a','r','m','v','7','-','a',' ','-','m','a','n','d','r',
        'o','i','d',' ','-','I','/','i','n','c','l','u','d','e',' ','-','B','/',
        'l','i','b',' ','-','O','3',' ','-','f','o','m','i','t','-','f','r','a',
        'm','e','-','p','o','i','n','t','e','r',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: android-armv7"
    #define DATE "built on: Tue Mar 29 04:56:44 2016"
#endif
